export const gotraList = [
'Aditya',
'Adiyta Rushi',
'Agatsya Rushi',
'Ampantar Rushi',
'Angira Rushi',
'Angiras Rushi',
'Ansuri Rushi',
'Arpama Rushi',
'Asit Rushi',
'Atri Rushi',
'Bharadwaj Rushi',
'Bhrugu Rushi',
'Bodhya Rushi',
'Chyavan',
'Dadhichi Rushi',
'Deval Rushi',
'Dwix Rushi',
'Galav Rushi',
'Gautam Rushi',
'Hiranyalabh',
'Jamadagni Rushi',
'Jhatukanva Rushi',
'Kapil Rushi',
'Karanya Rushi',
'Kartik Rushi',
'Karwas Rushi',
'Kashyap Rushi',
'Kaushalya Rushi',
'Kaushik Rushi',
'Kratu Rushi',
'Krupacharya Rushi',
'Maitriya rushi',
'Markand Rushi',
'Martand Rushi',
'Mitrudev Rushi',
'Parashar Rushi',
'Patanjali Rushi',
'Pipalad Rushi',
'Pulah Rushi',
'Pulatsya Rushi',
'Romesh Rushi',
'Ruchik',
'Shandilya',
'Shibhari Rushi',
'Shonak Rushi',
'Shrungi Rushi',
'Shrutdev Rushi',
'Twashtha Rushi',
'Uttang Rushi',
'Valmiki Rushi',
'Vashisht Rushi',
'Vedasira Rushi',
'Yaghyavalk Rushi',
'Yavarav Rushi'
];
