from flask import jsonify
from . import app
from werkzeug.http import HTTP_STATUS_CODES


# 404 and 500 are errors generated by Flask
@app.errorhandler(404)
def page_not_found(e):
    response = jsonify({'error': 'not found'})
    response.status_code = 404
    return response

@app.errorhandler(500)
def internal_server_error(e):
    response = jsonify({'error': 'internal server error'})
    response.status_code = 500
    return response

# These errors are generated by our app
def error_response(status_code, message=None):
    payload = {'error': HTTP_STATUS_CODES.get(status_code, 'Unknown error')}
    if message:
        payload['message'] = message
    response = jsonify(payload)
    response.status_code = status_code
    return response

# helper function for 400 error as it is very common
def bad_request(message):
    return error_response(400, message)

