"""many to many fix

Revision ID: 1e8f93bfe990
Revises: 54a6d0f6629b
Create Date: 2020-05-26 18:02:57.326683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e8f93bfe990'
down_revision = '54a6d0f6629b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_marital',
    sa.Column('user_details_id', sa.Integer(), nullable=False),
    sa.Column('marital_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marital_status_id'], ['marital_status.id'], ),
    sa.ForeignKeyConstraint(['user_details_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('user_details_id', 'marital_status_id')
    )
    op.drop_table('userdetails_marital')
    op.add_column('country', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('country', sa.Column('update_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'update_date')
    op.drop_column('country', 'name')
    op.create_table('userdetails_marital',
    sa.Column('ud_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ms_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ms_id'], ['marital_status.id'], name='userdetails_marital_ibfk_1'),
    sa.ForeignKeyConstraint(['ud_id'], ['user_details.id'], name='userdetails_marital_ibfk_2'),
    sa.PrimaryKeyConstraint('ud_id', 'ms_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_marital')
    # ### end Alembic commands ###
