"""increae token length

Revision ID: 962023649d4f
Revises: b1a724e8ea6c
Create Date: 2020-05-21 22:50:40.375389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '962023649d4f'
down_revision = 'b1a724e8ea6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'token',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=140),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'token',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
